### ISSUE TITLE
Doubt in code related to server tick number

### ISSUE THREAD

**Issue by Rafaesp** [spectre1989/unity_physics_csp#3]
Hi!
I've read your article and it's awesome. Congratulations.

I'm wondering why this line
https://github.com/spectre1989/unity_physics_csp/blob/e90e30d7d54cd7bdd27fdfbc01ad66ed180d9933/Assets/Logic.cs#L257
 doesn't look like the one in your article:
`state_msg.tick_number = input_msg.tick_number + 1;`

I think it should be something like `max_tick+1`. Am I missing something?

Thanks!

**Comment by spectre1989** [comment]
In the article when I have:
`state_msg.tick_number = input_msg.tick_number + 1;`
The server is simulating a single tick per input message, so the tick number of the state message it sends back is the tick number of the input message + 1.

When the client starts sending a list of redundant inputs, this can result in the server simulating multiple ticks from one input message.

However, in the code, I only update the server_tick_number with max_tick + 1 after the loop of simulating ticks - and most importantly AFTER the state message has been sent! This is indeed a bug, great catch!

I've submitted a fix [here](https://github.com/spectre1989/unity_physics_csp/commit/bbc12b62222e7f27c2588ebcb3dc74d91cede27a), movement now feels a lot better with heavy lag/packet loss now, thanks very much for pointing this out! :)

**Comment by Rafaesp** [comment]
Awesome!
Thanks
